name: dropbox_example
description: Demonstrates how to use the dropbox plugin.
publish_to: 'none'
version: 0.5.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+3
  path_provider: ^1.6.8
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  dropbox_client:
    path: ../

flutter:
  uses-material-design: true
